language: cpp

compiler:
  - gcc
  
before_install:
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

before_script:  
    - mkdir build
    - cd build
    - cmake -G "Unix Makefiles" ..

script: 
    - make test && make
    - ls -a
    - ./runAlgorithmTest
